# REQUIRED TASK ITEMS
# name of the sns output subdirectory from which to take input files 
input_dir: 'BAM-GATK-RA-RC'

# filename pattern to use for input file
input_pattern: '*.dd.ra.rc.bam'

# name of the parent directory to use for the program output
output_dir_name: QC-Coverage-Custom

# report file basename
report_files: GATK_DepthOfCoverage_custom_report.Rmd


# TASK SPECIFIC CUSTOM ITEMS
# https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_gatk_tools_walkers_coverage_DepthOfCoverage.php
# path to the GATK binary
bin: /ifs/data/molecpathlab/bin/GenomeAnalysisTK-3.8-0/GenomeAnalysisTK.jar

# path to reference genome file to use
ref_fasta: /local/data/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa

# coverage thresholds to measure
thresholds:
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500

# params for the GATK DepthOfCoverage program
minBaseQuality: 20
minMappingQuality: 20
nBins: 999
start: 1
stop: 1000
outputFormat: csv
readFilter: BadCigar
downsampling_type: NONE

