# ~~~~~ REQUIRED TASK ITEMS ~~~~~ #
# every sns_task should have these items

# name of the parent Python module
task_name: Summary_Avg_Coverage

# name of the sns output subdirectory from which to take input files 
input_dir: 'QC-coverage'

# filename pattern to use for input file
input_pattern: '*.sample_interval_summary'

# name of the parent directory to use for the program output
output_dir_name: Summary-Avg-Coverage
# i.e. analysis_dir/QC-Coverage-Custom will be used

# # path to the `reports` directory relative to the `sns_tasks` dir
# # dont change this!
# report_dir: reports
# # ^ i.e. same as sns_tasks/reports

# files in the `report_dir` associated with this sns_task; should end in '_report.Rmd'
report_files: 
  - Summary_Avg_Coverage_report.Rmd

# # path to the `scripts` directory relative to the `sns_tasks` dir
# # dont change this!
# script_dir: scripts
# # ^ i.e. same as sns_tasks/scripts

# files in the `scripts_dir` associated with this sns_task
script_files: 
  - calculate_average_coverages.R
  - snsxt_tools.R


# ~~~~~ TASK SPECIFIC CUSTOM ITEMS ~~~~~ #
# script to run for the task
run_script: calculate_average_coverages.R
# annotation method to use with 'Annotation_inplace'
annotation_method: "ANNOVAR"