# ~~~~~ REQUIRED TASK ITEMS ~~~~~ #
# every sns_task should have these items

# name of the task as listed in the Python class implementation
task_name: template_task

# name of the sns output subdirectory from which to take input files 
input_dir: 'VCF-GATK-HC-annot'

# name of the parent directory to use for the program output
output_dir_name: Template-Task
# i.e. analysis_dir/QC-Coverage-Custom will be used

# files in the `report_dir` associated with this sns_task; should end in '_report.Rmd'
report_files: 
  - template_task_report.Rmd

# other files needed by the task
task_files:
  # - 'HapMap_GATKHC_variants.tsv'


# ~~~~~ ANALYSIS TASK ITEMS ~~~~~ # 
# use these if the task will operate on the analysis as a whole

input_files: 
  - 'baz.txt'

# files that should be output by the analysis task
output_files:
  - 'foo.txt'
  - 'bar.txt'

# ~~~~~ SAMPLE TASK ITEMS ~~~~~ # 
# use these if the analysis task will operate on each sample individually

# suffix to append to sample ID for expected input file
input_suffix: '.combined.txt'

# suffix to append to sample ID for file produced by this task
output_suffix: '.combined.txt'

# list of suffixes that should be output for every sample in the analysis
output_suffixes: 
  - '.sample_cumulative_coverage_counts'
  - '.sample_cumulative_coverage_proportions'
  - '.sample_interval_statistics'
  - '.sample_interval_summary'
  - '.sample_statistics'
  - '.sample_summary'



# ~~~~~ TASK SPECIFIC CUSTOM ITEMS ~~~~~ #

# path to binary file for task
# bin: