# settings to use globally across the 'snsxt' program

# ~~~~~ SNSXT MAIN SETTINGS ~~~~~ # 
# settings to configure the main program


# ~~~~~ SNS PIPELINE ~~~~~ #
# default settings for running an sns pipeline
sns_route: "wes"
sns_pairs_route: "wes-pairs-snv"
sns_repo_dir: 'sns'
# e.g.: snsxt/sns



# ~~~~~ SNSXT ANALYSIS TASKS SETTINGS ~~~~~ # 
# directories and locations for sns_tasks items
# subdirectories of snsxt/sns_tasks/
tasks_scripts_dir: "scripts"
# ^ e.g. snsxt/sns_tasks/scripts
tasks_reports_dir: "reports"
tasks_config_dir: "config"
tasks_files_dir: "files"
tasks_sns_repo_dir: 'sns'


# ~~~~~ MAIL ~~~~~ # 
# settings to use when sending email from the pipeline
# email addresses to send results to; format is 'email1@server.com,email2@server.com'
email_recipients: '#MolecularPathology@nyumc.org'

# files to include in the email output from the parent analysis dir
mail_files:
  - "RunParameters.xml"
  - "RunParameters.txt"
  - "summary-combined.wes.csv"



# ~~~~~ REPORT ~~~~~ #
# settings to use when setting up the reports for the pipeline

# script to use to compile the RMD reports
report_compile_script: compile_RMD_report.R
# ^ i.e. snsxt/snsxt/compile_RMD_report.R

# path to the `report` directory relative to the `snsxt` dir
# dont change this!
report_dir: report
# ^ i.e. same as snsxt/snsxt/report

# files in the `report_dir` associated with this sns_task
# parent report file
main_report: analysis_report.Rmd

# supporting report files
report_files: 
  - report_tools.R
  - report_config.yml
  - report_styles.css
  - summary_report.Rmd
  - variant_report.Rmd
  - paired_variant_report.Rmd

# files to read run meta data from 
# !! This also needs to be set in snsxt/config/snsxt.yml !! 
analysis_id_file: analysis_id.txt
results_id_file: results_id.txt
samples_fastq_raw_file: samples.fastq-raw.csv
summary_combined_file: summary-combined.wes.csv
samples_pairs_file: "samples.pairs.csv"
GATK_HC_annot_file: "summary.VCF-GATK-HC-annot.csv"
GATK_summary_file: "VCF-GATK-HC-annot.all.txt"
LoFreq_annot_file: "summary.VCF-LoFreq-annot.csv"
LoFreq_summary_file: "VCF-LoFreq-annot.all.txt"
# dirs for the tumor-normal paired variant calling output;
# these may or may not exist depending how sns was run
# MuTect2_vcf_dir: "VCF-MuTect2-test"
# MuTect2_annot_dir: "VCF-MuTect2-annot-test"
# Strelka_vcf_dir: "VCF-Strelka-test"
# Strelka_annot_dir: "VCF-Strelka-annot-test"
MuTect2_annot_file: "VCF-MuTect2-annot.all.txt"
MuTect2_summary_file: "summary.VCF-MuTect2-annot.csv"
Strelka_annot_file: "VCF-Strelka-annot.all.txt"
Strelka_summary_file: "summary.VCF-Strelka-annot.csv"

