# directories where each report should look for its input files
# put these in the order which they should appear in the report
report_input_dirs:
  # key: value
  # report_file.Rmd: input_dir
  GATK_DepthOfCoverage_custom_report.Rmd: QC-Coverage-Custom
  

# patterns of dirs to exclude from inclusion in the report
report_exclude_dirs: 
  - 'snsxt*'
