# settings used by the R Markdown reports

# directories for the 'known' expected child documents
# directories where each report should look for its input files
# put these in the order which they should appear in the report
# input_dir is relative to the top level of the analysis directory
report_input_dirs:
  # key: value
  # report_file.Rmd: input_dir
  summary_report.Rmd: "."
  Summary_Avg_Coverage_report.Rmd: "Summary-Avg-Coverage"
  GATK_DepthOfCoverage_custom_report.Rmd: "QC-Coverage-Custom"
  
  

# patterns of dirs to exclude from inclusion in the report
report_exclude_dirs: 
  - 'snsxt*'

# files to read run meta data from 
# !! This also needs to be set in snsxt/config/snsxt.yml !! 
analysis_id_file: analysis_id.txt
results_id_file: results_id.txt
samples_fastq_raw_file: samples.fastq-raw.csv
summary_combined_file: summary-combined.wes.csv
