email_recipients_file: /ifs/data/molecpathlab/scripts/email_recipients.txt
nextseq_dir: /ifs/data/molecpathlab/quicksilver
run_monitor_log_dir: /ifs/data/molecpathlab/scripts/run-monitor/logs
script_dir: /ifs/data/molecpathlab/scripts