version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '[%(asctime)s] %(levelname)s (%(name)s:%(module)s:%(funcName)s:%(lineno)d) %(message)s'
  console:
    format: '[%(asctime)s] %(levelname)s (%(name)s:%(funcName)s:%(lineno)d) %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
  email:
    format: '[%(levelname)-8s] %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  main:
    () : __main__.logpath
    level: DEBUG   
    formatter: default
  email:
    () : __main__.email_logpath
    level: INFO   
    formatter: email

loggers:
  run:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  config:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  tools:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  find:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  git:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  qsub:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  task_func:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  setup_report:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
  mail:
    level: DEBUG
    handlers: [console, main, email]
    propagate: true
