# tasks I am working on testing and developing for the pipeline
tasks:
  DemoQsubSampleTask: 
    qsub_wait: True
  # GATKDepthOfCoverageCustom: 
  #   qsub_wait: False
  # Delly2: 
  #   qsub_wait: False
  # HapMapVariantRef:

setup_report: False