# tasks I am working on testing and developing for the pipeline

# sns analysis setup tasks
sns:
  StartSns: # new sns pipeline
  # SnsWes: # WES pipeline with unpaired variant calling
  SnsSetupPairs: # copy over the user's "samples.pairs.csv" sheet for downstream custom usage
  # SnsWesPairsSnv: # sns tumor-normal paired variant calling pipeline

# downstream analysis tasks
tasks:
  MuTect2Split:
  # DemoMultiQsubSampleTask:
  # DemoQsubSampleTask: 
  #   qsub_wait: False
  # DemoQsubAnalysisTask:
  #   qsub_wait: False

setup_report: False
